Repository bottlenose-dolphins/worldgate-track-trace, pull requests merged in 2023-01, with the labels that each got.

#9 [BDTT-35] Precommit hooks for FE changes
  app/.eslintrc.json
  app/.husky/pre-commit
  app/.prettierrc
  app/package-lock.json
  app/package.json
  app/src/App.jsx
  app/src/App.test.js
  app/src/App.test.jsx
  app/src/index.jsx
  app/src/reportWebVitals.js
  app/src/setupTests.js
Labels: frontend, ready to review

#10 [BDTT-14, BDTT-15, BDTT-16] Static FE components and page for customer Sign In
  app/src/components/signIn/PasswordInput.jsx
  app/src/components/signIn/UsernameInput.jsx
  app/src/components/signIn/index.jsx
  app/src/img/SignInBackground.png
  app/src/img/TrackAndTrace.png
Labels: frontend, ready to review

#12 Bdtt 6,7,8,9,33
  app/package-lock.json
  app/package.json
  app/src/App.jsx
  app/src/components/signIn/index.jsx
  app/src/components/signUp/emailInput.jsx
  app/src/components/signUp/index.jsx
  app/src/components/signUp/nameInput.jsx
  app/src/components/signUp/passwordInput.jsx
  app/src/components/signUp/phoneInput.jsx
  app/src/components/signUp/registerButton.jsx
  app/src/components/signUp/usernameInput.jsx
  app/src/img/SignUpBackground.png
  app/src/routes/index.jsx
  app/src/routes/signUp/index.jsx
Labels: frontend, ready to review

#11 Page Routing for Sign Up Page
  app/src/App.jsx
  app/src/components/signIn/index.jsx
  app/src/components/signUp/index.jsx
  app/src/routes/index.jsx
  app/src/routes/signUp/index.jsx
Labels: frontend, ready to review

#13 added scraper for yang ming shipping line
  scrapers/ymluScraper.py
Labels: enhancement, backend, ready to review

#15 BDTT-30
  webscrapers/goodrich.py
  webscrapers/requirements.txt
Labels: backend, ready to review

#17 [BDTT-36] Integrate BE Sign In API with FE
  app/.env-example
  app/.gitignore
  app/README.md
  app/package-lock.json
  app/package.json
  app/src/api/config.js
  app/src/api/user.js
  app/src/components/signIn/PasswordInput.jsx
  app/src/components/signIn/index.jsx
  backend/.env-example
  backend/README.md
  backend/app/user.py
  backend/requirements.txt
Labels: frontend, ready to review

#23 [BDTT-25] KMTC Line Web Scraper
  scrapers/kmtcScraper.py
Labels: enhancement, backend, ready to review

#22 [BDTT-37] Completed full integration of sign up process
  .gitignore
  app/src/api/user.js
  app/src/components/signUp/emailInput.jsx
  app/src/components/signUp/index.jsx
  app/src/components/signUp/nameInput.jsx
  app/src/components/signUp/passwordInput.jsx
  app/src/components/signUp/phoneInput.jsx
  app/src/components/signUp/registerButton.jsx
  app/src/components/signUp/registerModal.jsx
  app/src/components/signUp/usernameInput.jsx
  backend/.gitignore
  backend/app/user.py
Labels: enhancement, backend, ready to review

#24 [BDTT-24] JWT Token-based Authentication with Cookies
  app/package-lock.json
  app/package.json
  app/src/App.jsx
  app/src/api/config.js
  app/src/api/user.js
  backend/README.md
  backend/app/user.py
  backend/requirements.txt
Labels: backend, ready to review
